import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const API_URL = 'http://localhost:3000/api/seo/ai/social';
// Using a placeholder key since the API mocks the response anyway based on the 'contentTitle'.
// If real AI logic is added later, this script will need a real key.
const MOCK_API_KEY = 'mock-gemini-key-for-generation';

const WEEKLY_PLAN = [
    { day: 'Monday', topic: 'Best Monday Coffee', type: 'Motivation' },
    { day: 'Tuesday', topic: 'Spicy Paneer Pizza', type: 'Product Showcase' },
    { day: 'Wednesday', topic: 'Veggie Supreme Burger', type: 'Mid-week Cravings' },
    { day: 'Thursday', topic: 'Chocolate Thick Shake', type: 'Thirsty Thursday' },
    { day: 'Friday', topic: 'Family Combo Meal', type: 'Weekend Offer' },
    { day: 'Saturday', topic: 'Dine-in Experience', type: 'Visual Vibes' },
    { day: 'Sunday', topic: 'Sunday Funday Desserts', type: 'Family Time' }
];

async function generateContent() {
    console.log('🚀 Starting Weekly Content Generation...\n');
    let markdownOutput = `# 📅 Oye Chatoro: Weekly Social Media Calendar\n\nGenerated by SEO Dashboard AI on ${new Date().toLocaleDateString()}\n\n`;

    for (const item of WEEKLY_PLAN) {
        console.log(`Generating for ${item.day}: ${item.topic}...`);

        // Add delay to avoid rate limits
        await new Promise(resolve => setTimeout(resolve, 3000));

        try {
            const response = await fetch(API_URL, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    contentTitle: item.topic,
                    type: item.type
                })
            });

            if (!response.ok) {
                throw new Error(`API Error: ${response.status}`);
            }

            const data = await response.json();
            if (data.debugError) console.error("Server Debug Error:", data.debugError);
            if (data.captions[0] && data.captions[0].startsWith('ERROR:')) console.error("AI Error:", data.captions[0]);

            const bestCaption = data.captions[0]; // Take the first one for the calendar
            const prompt = data.imagePrompt || "*No prompt generated*";

            markdownOutput += `## ${item.day} - ${item.topic}\n`;
            markdownOutput += `**Strategy**: ${item.type}\n\n`;
            markdownOutput += `**📸 Suggested Caption**:\n> ${bestCaption}\n\n`;
            markdownOutput += `**🎨 AI Image Prompt**:\n> ${prompt}\n\n`;
            markdownOutput += `**#️⃣ Hashtags**:\n\`#AbuRoad #OyeChatoro #${item.type.replace(/\s/g, '')}\`\n\n`;
            markdownOutput += `---\n\n`;

        } catch (error) {
            console.error(`Example failed for ${item.day}:`, error.message);
            markdownOutput += `## ${item.day} - ${item.topic}\n*Generation Failed*\n\n---\n\n`;
        }
    }

    const outputPath = path.join(__dirname, '..', 'weekly_content_calendar.md');
    fs.writeFileSync(outputPath, markdownOutput);
    console.log(`\n✅ Calendar generated at: ${outputPath}`);
}

generateContent();
